/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./components/atoms/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/atoms/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./components/atoms/BaseInput.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/molecules/SearchBar.vue')['default']
    TodoForm: typeof import('./components/organisms/TodoForm.vue')['default']
    TodoItem: typeof import('./components/molecules/TodoItem.vue')['default']
    TodoList: typeof import('./components/organisms/TodoList.vue')['default']
  }
}
