/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./components/atoms/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/atoms/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./components/atoms/BaseInput.vue')['default']
    DailyGreeting: typeof import('./components/organisms/DailyGreeting.vue')['default']
    EarningsClock: typeof import('./components/organisms/EarningsClock.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MobileBottomNav: typeof import('./components/organisms/MobileBottomNav.vue')['default']
    MyDay: typeof import('./components/organisms/MyDay.vue')['default']
    ProductivityHeatmap: typeof import('./components/organisms/ProductivityHeatmap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/molecules/SearchBar.vue')['default']
    SettingsPanel: typeof import('./components/organisms/SettingsPanel.vue')['default']
    StatisticsCard: typeof import('./components/organisms/StatisticsCard.vue')['default']
    ThemeToggle: typeof import('./components/molecules/ThemeToggle.vue')['default']
    TodoForm: typeof import('./components/organisms/TodoForm.vue')['default']
    TodoItem: typeof import('./components/molecules/TodoItem.vue')['default']
    TodoList: typeof import('./components/organisms/TodoList.vue')['default']
    WeatherWidget: typeof import('./components/organisms/WeatherWidget.vue')['default']
  }
}
